/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as EspaceFormationRouteImport } from './routes/espace-formation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormationsIndexRouteImport } from './routes/formations.index'
import { Route as FormationsKeyRouteImport } from './routes/formations.$key'

const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceFormationRoute = EspaceFormationRouteImport.update({
  id: '/espace-formation',
  path: '/espace-formation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsIndexRoute = FormationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormationsRoute,
} as any)
const FormationsKeyRoute = FormationsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => FormationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/espace-formation': typeof EspaceFormationRoute
  '/formations': typeof FormationsRouteWithChildren
  '/formations/$key': typeof FormationsKeyRoute
  '/formations/': typeof FormationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/espace-formation': typeof EspaceFormationRoute
  '/formations/$key': typeof FormationsKeyRoute
  '/formations': typeof FormationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/espace-formation': typeof EspaceFormationRoute
  '/formations': typeof FormationsRouteWithChildren
  '/formations/$key': typeof FormationsKeyRoute
  '/formations/': typeof FormationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/espace-formation'
    | '/formations'
    | '/formations/$key'
    | '/formations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/espace-formation'
    | '/formations/$key'
    | '/formations'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contact'
    | '/espace-formation'
    | '/formations'
    | '/formations/$key'
    | '/formations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EspaceFormationRoute: typeof EspaceFormationRoute
  FormationsRoute: typeof FormationsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-formation': {
      id: '/espace-formation'
      path: '/espace-formation'
      fullPath: '/espace-formation'
      preLoaderRoute: typeof EspaceFormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/': {
      id: '/formations/'
      path: '/'
      fullPath: '/formations/'
      preLoaderRoute: typeof FormationsIndexRouteImport
      parentRoute: typeof FormationsRoute
    }
    '/formations/$key': {
      id: '/formations/$key'
      path: '/$key'
      fullPath: '/formations/$key'
      preLoaderRoute: typeof FormationsKeyRouteImport
      parentRoute: typeof FormationsRoute
    }
  }
}

interface FormationsRouteChildren {
  FormationsKeyRoute: typeof FormationsKeyRoute
  FormationsIndexRoute: typeof FormationsIndexRoute
}

const FormationsRouteChildren: FormationsRouteChildren = {
  FormationsKeyRoute: FormationsKeyRoute,
  FormationsIndexRoute: FormationsIndexRoute,
}

const FormationsRouteWithChildren = FormationsRoute._addFileChildren(
  FormationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EspaceFormationRoute: EspaceFormationRoute,
  FormationsRoute: FormationsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
